export enum ProcessingDecision {
  AUTO_PROCESS = 'AUTO_PROCESS',
  HUMAN_REVIEW = 'HUMAN_REVIEW',
  REJECTED = 'REJECTED',
  TECHNICAL_FAILURE = 'TECHNICAL_FAILURE',
  BUSINESS_FAILURE = 'BUSINESS_FAILURE',
  RETRY_PENDING = 'RETRY_PENDING',
}
