export enum SupportTeam {
  IDENTITY_SUPPORT = 'IDENTITY_SUPPORT',
  BILLING_SUPPORT = 'BILLING_SUPPORT',
  TECHNICAL_SUPPORT = 'TECHNICAL_SUPPORT',
  ACCOUNT_SUPPORT = 'ACCOUNT_SUPPORT',
  SECURITY_OPERATIONS = 'SECURITY_OPERATIONS',
  GENERAL_SUPPORT = 'GENERAL_SUPPORT',
}
