export enum AuditEventType {
  QUEUE_ITEM_CLAIMED = "QUEUE_ITEM_CLAIMED",
  TICKET_RETRIEVED = "TICKET_RETRIEVED",
  TICKET_VALIDATED = "TICKET_VALIDATED",
  AI_CLASSIFICATION_COMPLETED = "AI_CLASSIFICATION_COMPLETED",
  BUSINESS_RULES_EVALUATED = "BUSINESS_RULES_EVALUATED",
  HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED",
  TICKET_UPDATE_STARTED = "TICKET_UPDATE_STARTED",
  TICKET_UPDATED = "TICKET_UPDATED",
  TICKET_UPDATE_VERIFIED = "TICKET_UPDATE_VERIFIED",
  QUEUE_ITEM_COMPLETED = "QUEUE_ITEM_COMPLETED",
  WORKFLOW_FAILED = "WORKFLOW_FAILED",
  RETRY_SCHEDULED = "RETRY_SCHEDULED",
}