export enum QueueItemStatus {
  NEW = "NEW",
  CLAIMED = "CLAIMED",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  HUMAN_REVIEW = "HUMAN_REVIEW",
  RETRY_PENDING = "RETRY_PENDING",
  DEAD_LETTER = "DEAD_LETTER",
}